sudo: required

services:
  - docker

before_install:
  - docker build -t benjtlv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true benjtlv/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "benjtlv-docker-react"
  env: "BenjtlvDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-664889048139"
  bucket_path: "benjtlv-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"